### ISSUE TITLE
problems checking out.

### ISSUE THREAD

**Issue by 5opr4ni** [nxtedition/nxt-graphics#2]
Having issues with this.

`run git submodule add git@github.com:nxtedition/nxt-graphics && cp -r ./nxt-graphics/setup/ ./`

```
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
```

Am I just stupid? Probably!

I am no king in ssh and what the prerequisite is before I can checkout in this manner .

<img width="438" alt="screen shot 2018-02-24 at 13 53 02" src="https://user-images.githubusercontent.com/20354852/36630637-2370ea46-196a-11e8-9196-6326bfcaab7d.png">

**Comment by ronag** [comment]
@5opr4ni I'm going to have a look over.
